#!/usr/bin/python3


r'''Converts model to the cameramodel file format

SYNOPSIS

  $ mrcal-to-cameramodel model.cahvor
  Wrote model.cameramodel


DESCRIPTION

This tool converts a given model to the cameramodel file format. No changes to
the content are made; this is purely a format converter. If the model is given
as "-", the input is read from standard input, and the output is written to
standard output

'''


from __future__ import print_function

import sys
import argparse
import re
import os

def parse_args():

    parser = \
        argparse.ArgumentParser(description = __doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)

    parser.add_argument('model',
                        type=str,
                        help='''Input camera model''')

    return parser.parse_args()

args = parse_args()

# arg-parsing is done before the imports so that --help works without building
# stuff, so that I can generate the manpages and README


import mrcal

if args.model == '-':
    m = mrcal.cameramodel(args.model)
    m.write(sys.stdout)
else:

    base,extension = os.path.splitext(args.model)
    if extension.lower() == '.cameramodel':
        sys.stderr.write("Input file is already in the cameramodel format (judging from the filename). Doing nothing\n")
        sys.exit()

    m = mrcal.cameramodel(args.model)
    filename_out = base + '.cameramodel'
    m.write(filename_out)
    print("Wrote " + filename_out)
