#!/usr/bin/python3

r'''Visualize the noncentral projection curve

SYNOPSIS

  $ mrcal-show-noncentral left.cameramodel

  ... a plot pops up showing the vector field of the difference from a pinhole
  projection


ADD MORE DOCS



'''


import sys
import argparse
import re
import os

def parse_args():

    parser = \
        argparse.ArgumentParser(description = __doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)


    parser.add_argument('--title',
                        type=str,
                        default = None,
                        help='''Title string for the plot. Overrides the default
                        title. Exclusive with --extratitle''')
    parser.add_argument('--extratitle',
                        type=str,
                        default = None,
                        help='''Additional string for the plot to append to the
                        default title. Exclusive with --title''')

    parser.add_argument('--hardcopy',
                        type=str,
                        help='''Write the output to disk, instead of making an interactive plot''')
    parser.add_argument('--terminal',
                        type=str,
                        help=r'''gnuplotlib terminal. The default is good almost always, so most people don't
                        need this option''')
    parser.add_argument('--set',
                        type=str,
                        action='append',
                        help='''Extra 'set' directives to pass to gnuplotlib. May be given multiple
                        times''')
    parser.add_argument('--unset',
                        type=str,
                        action='append',
                        help='''Extra 'unset' directives to pass to gnuplotlib. May be given multiple
                        times''')

    parser.add_argument('model',
                        type=str,
                        help='''Input camera model. If "-' is given, we read standard input''')

    return parser.parse_args()

args = parse_args()

if args.title      is not None and \
   args.extratitle is not None:
    print("--title and --extratitle are exclusive", file=sys.stderr)
    sys.exit(1)

# arg-parsing is done before the imports so that --help works without building
# stuff, so that I can generate the manpages and README




import numpy as np
import numpysane as nps
import gnuplotlib as gp

import mrcal





try:
    model = mrcal.cameramodel(args.model)
except Exception as e:
    print(f"Couldn't load camera model '{args.model}': {e}", file=sys.stderr)
    sys.exit(1)

lensmodel = model.intrinsics()[0]
if not re.match("LENSMODEL_SPLINED_STEREOGRAPHIC_", lensmodel):
    print(f"Only splined stereographic models have noncentral terms. This is not such a model", file=sys.stderr)
    sys.exit(1)

plotkwargs = {}
if args.set is not None:
    plotkwargs['set'] = args.set
if args.unset is not None:
    plotkwargs['unset'] = args.unset

if args.title is not None:
    plotkwargs['title'] = args.title
if args.extratitle is not None:
    plotkwargs['extratitle'] = args.extratitle

k = model.intrinsics()[1][-3:]

meta = mrcal.lensmodel_metadata_and_config(lensmodel)
fov_x_deg = meta['fov_x_deg']

th = np.linspace(0, fov_x_deg/2., 500)
u  = 2 * np.tan(th * np.pi/180. /2.)
dz = u*(k[0] + u*(k[1] + u*k[2]))

plot = gp.gnuplotlib(hardcopy     = args.hardcopy,
                     terminal     = args.terminal,
                     **plotkwargs)

plot.plot(th, dz,
          _with  = 'lines',
          xlabel = "Angle off optical axis (deg)",
          ylabel = "Noncentral deviation in z",
          title  = "Noncentral behavior")

if args.hardcopy is None:
    plot.wait()
