#!/usr/bin/python2

r'''Renders a difference in projection between two models

Synopsis:

  $ visualize-intrinsics-diff before.cameramodel after.cameramodel
  ... a plot pops up showing how two models differ in their projections
'''

import sys
import argparse
import os
import re

import mrcal.cahvor
import mrcal


def parse_args():

    parser = \
        argparse.ArgumentParser(description = __doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)

    parser.add_argument('--gridn',
                        type=int,
                        default = 40,
                        help='''How densely we should sample the imager. By default we report a 40x40 grid''')

    parser.add_argument('--extratitle',
                        type=str,
                        default = None,
                        help='''Extra title string for the plot''')

    parser.add_argument('--vectorfield',
                        action = 'store_true',
                        default = False,
                        help='''Plot the diff as a vector field instead of as a heat map. The vector field
                        contains more information (magnitude AND direction), but
                        is less clear at a glance''')

    parser.add_argument('--hardcopy',
                        type=str,
                        help='''Write the output to disk, instead of making an interactive plot''')
    parser.add_argument('--extraset',
                        type=str,
                        action='append',
                        help='''Extra 'set' directives to gnuplot. Can be given multiple times''')

    parser.add_argument('models',
                        type=lambda f: f if os.path.isfile(f) else \
                                parser.error("The cameramodel must be an existing readable file, but got '{}'".format(f)),
                        nargs='+',
                        help='''Camera models to diff''')

    args = parser.parse_args()

    if len(args.models) < 2:
        raise Exception("I need at least two models to diff. Instead got this: {}".format(args.models))

    return args



args = parse_args()

extraplotkwargs = {}
if args.extraset is not None:
    extraplotkwargs['set'] = args.extraset

def loadmodel(m):
    if re.match(".*\.cahvor$", m): return mrcal.cahvor.read(m)
    else:                          return mrcal.cameramodel(m)

models = [loadmodel(modelfilename) for modelfilename in args.models]

plot = mrcal.visualize_intrinsics_diff(models,
                                       args.gridn,
                                       args.vectorfield,
                                       hardcopy = args.hardcopy,
                                       extratitle=args.extratitle,
                                       extraplotkwargs = extraplotkwargs)
if args.hardcopy is None:
    import time
    time.sleep(1000000)
