#+TITLE: Copyrights and licenses

Copyright (c) 2017-2023 California Institute of Technology ("Caltech"). U.S.
Government sponsorship acknowledged. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

A number of free-software projects are included as source in the toolkit. These
are:

* [[https://github.com/dkogan/libminimath][libminimath]]
mrcal uses some tiny-matrix linear algebra routines implemented by this library.
This is a header-only library, so we're not "linking" to it. I'm not modifying
the sources, so using the LGPL here is fine, and doesn't trigger the copyleft
provisions. Copyright 2011 Oblong Industries. This library is distributed under
the terms of the GNU LGPL

* opencv projection
The [[https://www.github.com/dkogan/mrcal/blob/master/mrcal-opencv.c][opencv projection function]] is a cut-down implementation from the OpenCV
project. Distributed under an BSD-style license. Copyright (C) 2000-2008, Intel
Corporation, all rights reserved. Copyright (C) 2009, Willow Garage Inc., all
rights reserved.

* =mrcal_r_from_R()=
The [[https://www.github.com/dkogan/mrcal/blob/master/poseutils-opencv.c][=mrcal_r_from_R()= sources]] originated in the OpenCV project. Distributed
under an BSD-style license. Copyright (C) 2000-2008, Intel Corporation, all
rights reserved. Copyright (C) 2009, Willow Garage Inc., all rights reserved.

* [[file:mrcal-python-api-reference.html#-quat_from_R][=mrcal.quat_from_R()=]]
The [[https://www.github.com/dkogan/mrcal/blob/master/mrcal/_poseutils_scipy.py][=mrcal.quat_from_R()= sources]] came from scipy. Distributed under a
BSD-style license. Copyright (c) 2001-2002 Enthought, Inc. 2003-2019, SciPy
Developers.

* pydoc
[[https://www.github.com/dkogan/mrcal/blob/master/doc/pydoc.py][=doc/pydoc.py=]] is a copy of the sources in the Python project. This is used to
extract the docstrings into the .html reference documentation. Minor
modifications were made to fit with mrcal's code organization and html styling.
Distributed under the PYTHON SOFTWARE FOUNDATION LICENSE VERSION 2. Copyright
(c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
2013, 2014 Python Software Foundation; All Rights Reserved.

