#+title: mrcal - camera calibrations and more!

mrcal is a toolkit (originating at NASA/JPL) for working with lens models,
camera geometry, images, projections, and the various related operations such as
camera calibration. Any task that produces or consumes camera models can utilize
this toolkit. It was originally built to generate the high-accuracy calibrations
demanded by long-range stereo, so it provides facilities to analyze calibration
accuracy and to propagate and report uncertainties.

* Why mrcal?
In essense: because all other tools are terrible if you care about accuracy.
They make basic questions like "how much data should I gather for a
calibration?" and "how good is this calibration I just computed?" and "how
different are these two models?" unanswerable.

Big assumptions and obliviousness to sources of error are commonplace. This is
clearly seen from the core documentation on the subject. [[https://en.wikipedia.org/wiki/Camera_resectioning][The wikipedia article
on camera calibration]] only talks about fitting a pinhole model to lenses, even
though no real lenses follow this model (telephoto lenses do somewhat; wider
lenses don't at all). [[https://www.opencv.org][OpenCV]] is a dominant library in this area; its [[https://docs.opencv.org/master/dc/dbb/tutorial_py_calibration.html][calibration
tutorial]] cheerfully says that

#+begin_example
Re-projection error gives a good estimation of just how exact the found
parameters are. The closer the re-projection error is to zero, the more accurate
the parameters we found are.
#+end_example

This statement is trivially proven false: throw away most of your calibration
data, and your reprojection error becomes very low. But we can all agree that a
calibration computed from less data is actually worse. Right?

All the various assumptions and hacks in the existing tooling are fine as long
as you don't need a whole lot of accuracy out of your models.

mrcal is meant to address these shortcomings. This toolkit tries hard to allow
the user to produce calibrations that are as good as possible. It provides lots
of visualization capabilities to evaluate various properties of a model
solution. And it provides several powerful analysis methods, such as
quantification of projection and triangulation uncertainty. And model
differencing. And functions are provided to avoid making a pinhole-camera
assumption where it is not appropriate, such as with wide-angle stereo.

* Documentation index
Please see [[file:tour.org][a tour of mrcal]] for a high-level overview of the capabilities of the
toolkit.

First, the tools should be [[file:install.org][built or installed]].

Before using the tools, it is helpful to read about the [[file:conventions.org][terminology and
conventions]] used in the sources and documentation.

At the core of a calibration routine is an optimization problem. Details about
its [[file:formulation.org][formulation]] are useful to be able to interpret the results.

A lens can be represented by any of a number of [[file:lensmodels.org][lens models]].

A [[file:how-to-calibrate.org][how-to-calibrate-some-cameras]] page describes details about how to accomplish
this very common task.

After running a calibration, the camera models are written to [[file:cameramodels.org][files on disk]].

We can then use these files with a number of [[file:commandline-tools.org][command-line tools]]. In particular,
we can [[file:differencing.org][compare the projection behaviors of different models]]. And we can [[file:uncertainty.org][compute
the projection uncertainties]] of a model.

If we need to do something more than what the pre-made tools can do, there're
two sets programmatic interfaces available:

- [[file:c-api.org][The C API to provide a set of core functionality]]
- [[file:python-api.org][The Python API to do that and a whole lot more]]

* Citing
To cite this work in a publication, use this bibtex stanza:

#+begin_example
@misc{mrcal,
  author = "Dima Kogan",
  title = "mrcal",
  howpublished = "\url{http://mrcal.secretsauce.net}",
}
#+end_example

* Dev communication
For now let's use the [[https://github.com/dkogan/mrcal/issues][github issue tracker]] for bug reporting and for
communication in general. At some point I will probably set up a mailing list as
well.

* Author
Dima Kogan =dima@secretsauce.net=

* License and copyright
Copyright (c) 2017-2021 California Institute of Technology ("Caltech"). U.S.
Government sponsorship acknowledged. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

There's some included external code in the sources, with their own [[file:copyrights.org][copyrights
and licenses]].


