#+title: mrcal - camera calibrations and more!

mrcal is a toolkit (originating at NASA/JPL) for working with lens models,
camera geometry, images, projections, and the various related operations such as
camera calibration. Any task that produces or consumes camera models can utilize
this toolkit. It was originally built to generate the high-accuracy calibrations
demanded by long-range stereo, so it provides facilities to analyze calibration
accuracy and to propagate and report uncertainties.

[[https://docs.opencv.org/master/][OpenCV]] is a library often used to solve similar problems. It can't produce
calibrations that are as good as mrcal's, and it can't report on how good its
results really are.

* Documentation index

Please see [[file:tour.org][a tour of mrcal]] for a high-level overview of the capabilities of the
toolkit.

First, the tools should be [[file:install.org][built or installed]].

Before using the tools, it is helpful to read about the [[file:conventions.org][terminology and
conventions]] used in the sources and documentation.

At the core of a calibration routine is an optimization problem. Details about
its [[file:formulation.org][formulation]] are useful to be able to interpret the results.

A lens can be represented by any of a number of [[file:lensmodels.org][lens models]].

A [[file:how-to-calibrate.org][how-to-calibrate-some-cameras]] page describes details about how to accomplish
this very common task.

After running a calibration, the camera models are written to [[file:cameramodels.org][files on disk]].

We can then use these files with a number of [[file:commandline-tools.org][command-line tools]]. In particular,
we can [[file:differencing.org][compare the projection behaviors of different models]]. And we can [[file:uncertainty.org][compute
the projection uncertainties]] of a model.

If we need to do something more than what the pre-made tools can do, there're
two sets programmatic interfaces available:

- [[file:c-api.org][The C API to provide a set of core functionality]]
- [[file:python-api.org][The Python API to do that and a whole lot more]]

* Author
Dima Kogan =dima@secretsauce.net=

* License and copyright
Copyright (c) 2017-2020 California Institute of Technology ("Caltech"). U.S.
Government sponsorship acknowledged. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

There's some included external code in the sources, with their own [[file:copyrights.org][copyrights
and licenses]].

* future work                                                      :noexport:
** uncertainty/noise computations
*** Noted in uncertainty.org
- measure observed_pixel_uncertainty
- improve uncertainty method: faraway obervations don't make things worse
- projection_uncertainty() should be able to project multiple points at a time,
  and to report correlations in the projection. Should work with multiple
  cameras somehow (could calibration more than one camera at the same time)
*** Not noted in uncertainty.org
- use uncertainty in triangulation, deltapose, stereo
- can I quantify the heteroscedasticity and thus the model-nonfitting and the
  resulted expected bias? White test?
- do a triangulation with explict uncertainty propagation
- uncertainty math currently does a separate mean-frames for each q we ask
  about. Thus we're effectively computing a different implied tranform each
  time. We should have a single one for ALL q
- regions without chessboards (like in the talk): why do we see high
  uncertainty? That's what I /want/, but I don't think it should be working: the
  spline is dominated by the regularization terms there, so the lens model is
  purely stereographic. Oh... am I seeing /just/ the noise in the chessboard
  pose? I can't rely on that
** splined models
*** noted in lensmodels.org
- splined models should behave more nicely at the edges
- better regularization scheme for the non-splined models. Can I do better than
  L2? Surely I can
- better regularization scheme for the splined models. I should pull not towards
  0 but towards the mean. I had an implementation in
  c8f9918023142d7ee463821661dc5bcc8f770b51 that I reverted because any planar
  splined surface would have "perfect" regularization, and that was breaking
  things (crazy focal lengths would be picked). But now that I'm locking down
  the intrinsics core when optimizing splined models, this isn't a problem anymore

#+begin_example
Notes from sources:

splined regularization should penalize dqx/dvx<0. It should be >0 everywhere.
The splined representation COULD flip that around, however, and I should fight
that. This would make the function non-reversible uniquely, and unproject()
could have trouble

  q = (u + deltau(u)) * f + c
  dqx/dpx ~ (d(ux + deltaux(u))/dpx) =
          = dux/dpx + ddeltaux(u)/du du/dpx
  u = xy / (mag_p + z) * 2, so
  dqx/dpx ~ ((mag_p + z) - x^2/mag_p)/(mag_p + z)^2 +
            ddeltaux(u)/du ((mag_p + z) I - outer(xy,xy)/mag_p)/(mag_p + z)^2
  I care about the sign only, so
  dqx/dpx ~ (mag_p + z) - x^2/mag_p +
#+end_example

- study cubic/quadratic splines, spline density effects
** diff
*** noted in lensmodels.org
- projection_diff(): weighting should be better. Should I do outlier rejection?
  Should I use the hoaky valid-intrinsics region to cut down the fit set? Should
  I optimize actual reprojection error?
** stuff to add
- better sfm support
- integrate deltapose-lite (lindstrom-optimized points) into mrcal
- cahvore linearity should be a config parameter
- cahvore: non-gradientness should be a metadata parameter
- better outlier rejection. cook's D
- outlier rejection for points AND board observations
*** stereo
- stereo.py should be a separate tool, like jplv stereo
- add the good triangulate-feature tool to mrcal/stereo.py
** stuff to study
- Redo, show stability. Heat? Show effects?
- Can we study intrinsics stability over time? In response to heating? Shaking?
- Can we use a 3-parallel calibration to quantify chromatic aberration?
- Measure effect of focus, aperture

** warnings in mrcal.c
[[file:~/jpl/mrcal/mrcal.c::// WARNING: if I could assume that dq_dintrinsics_pool_double!=NULL then I wouldnt need to copy the context][something about being efficient and not copying stuff]]

[[file:~/jpl/mrcal/mrcal.c::// WARNING: This should go away. For some reason it makes unproject() converge better, and it makes the tests pass. But it's not even right!][=mrcal_unproject_internal()=]] is seeding the optimization in a 100% wrong way
that, for some reason, works better than if I fix the bug. Fixing the bug makes
the tests fail

[[file:~/jpl/mrcal/mrcal.c::// WARNING: sparsify this. This is potentially a BIG thing on the stack][not putting the full optimization state on the stack]]

[[file:~/jpl/mrcal/mrcal.c::// WARNING: "compute size(dq_dintrinsics_pool_double) correctly and maybe bounds-check"][Again: don't put the full intrinsics on the stack]]

mrcal_optimize(): merge =packed_state= and =p_packed_final=. And =packed_state=
is a big stack thing, which is scary

Hook up the =// optimizer_callback(packed_state, NULL, NULL, &ctx);= calls.
These are supposed to do diagnostics only, or something. Look at what deltapose
is doing.

* todo for the document                                            :noexport:
stereo. Try opencv rectification

something somewhere should describe the optimizer_callback()

Somewhere talk about these:
  - [[file:mrcal-python-api-reference.html#-ingest_packed_state][=mrcal.ingest_packed_state()=]]: Read a given packed state into optimization_inputs
  - [[file:mrcal-python-api-reference.html#-corresponding_icam_extrinsics][=mrcal.corresponding_icam_extrinsics()=]]: Return the icam_extrinsics corresponding to a given icam_intrinsics
    talk about this next to optimization_inputs()

talk about --seed and how that can be used to validate intrinsics

add punchline note at the end of the tour

