#+title: Building or installing

I provide packages for a number of distros. If possible, please use these
instead of building from source. If you're interested in packages for a
not-yet-supported distro, please contribute! Email me for help.

* Installing from packages
** Debian-based
As of today (2022-02-27), mrcal is included in the bleeding-edge versions of
Debian and Ubuntu. So if you're running at least Debian/testing or the
not-yet-published Debian 12 (bookworm) or Ubuntu 22.04 (jammy), you can
simply

#+begin_src sh
apt install mrcal libmrcal-dev python3-mrcal
#+end_src

to install the commandline tools and the C development library and the Python
library respectively.

For older distros I currently distribute packages for

- Debian/buster
- Debian/bullseye
- Ubuntu/focal (20.04 LTS)
- Ubuntu/bionic (18.04 LTS)

To use these, add to your =/etc/apt/sources.list=:

#+begin_example
deb [trusted=yes] http://mrcal.secretsauce.net/packages/DISTRO/public/ DISTRO main
#+end_example

where =DISTRO= is one of

- =buster=
- =bulleye=
- =focal=
- =bionic=

Then, =apt update && apt install mrcal=. The chessboard corner finder, while not
strictly required, is needed if you're doing chessboard-based calibrations. =apt
install mrgingham=

* Building from source
If you cannot use the packages for whatever reason, you must build from source.
This isn't /difficult/, but requires you to obtain all the dependencies. They're
listed in the =Build-Depends= section of the [[https://salsa.debian.org/science-team/mrcal/-/blob/master/debian/control][debian package definition]]. Most of
these are available in most distros. Things that may not be:

- =libdogleg-dev=: the optimization library. Sources live [[https://github.com/dkogan/libdogleg/][here]]. You need at
  least version 0.15.3.

- =vnlog=: the toolkit to manipulate textual tables. Sources live [[https://github.com/dkogan/vnlog/][here]]. You only
  /need/ this for the test suite. There's nothing to build. Simply downloading
  the sources and pointing the =PATH= there is sufficient.

- =python3-numpysane=: The make-numpy-reasonable library from [[https://github.com/dkogan/numpysane/][here]]. You
  absolutely need at least version 0.35. Available in the usual places Python
  libraries live. This is a python-only library. Simply downloading the sources
  and pointing the =PYTHONPATH= there is sufficient.

- =python3-gnuplotlib=: The plotting library from [[https://github.com/dkogan/gnuplotlib/][here]]. You need at least
  version 0.38. Available in the usual places Python libraries live. This is a
  python-only library. Simply downloading the sources and pointing the
  =PYTHONPATH= there is sufficient.

- =mrgingham=: the chessboard corner finder. This isn't strictly a requirement -
  any corner finder can be used. If you want to use this one (and you can't use
  the packages), you need to build it. Sources live [[https://github.com/dkogan/mrgingham/][here]].

- =re2c=: parser-generator for the C code to parse =.cameramodel= files. At
  least version 2 is required.

Once these are all downloaded, =libdogleg= and =re2c= built and the =PATH= and
=PYTHONPATH= set, we can build mrcal. The child processes need access to the
=PATH= and =PYTHONPATH=, so

#+begin_src sh
export PATH
export PYTHONPATH
#+end_src

If you "installed" =libdogleg= somehow, then you're ready, so just =make=.
Otherwise, tell the build about where the built =libdogleg= is:

#+begin_src sh
LIBDOGLEGDIR=....
CFLAGS=-I$LIBDOGLEGDIR LDFLAGS="-L$LIBDOGLEGDIR -Wl,-rpath=$LIBDOGLEGDIR"  make
#+end_src

If that works, the test suite should all pass:

#+begin_src sh
make test-nosampling
#+end_src

If stuff doesn't work, feel free to bug me. But you /really/ should be using the
packages, if at all possible

* code                                                             :noexport:
Build, upload each package like this:

#+begin_src sh

distro=bionic;

perl -p -i -e 'if($. == 1) { s/[a-z]+;/'"$distro;/; }" debian/changelog && \
sbuild \
  --nolog \
  --no-apt-{update,upgrade} -d $distro -A \
  --no-source -c $distro-amd64 \
  --anything-failed-commands '%s' \
  --extra-repository="deb [trusted=yes] http://mrcal.secretsauce.net/packages/$distro/public/ $distro main" -j 3 && \
debsign -k 751C135DC2CE0143380854F3ED63B6125A1D1561 ../*.changes(om[1]) && \
dput digitalocean_mrcal_$distro ../*.changes(om[1])
#+end_src

